module.exports = {
    ACTIONS: {
        GET_PENDING_EMAILS: 'GET_PENDING_EMAILS',
        SEND_TEMPLATE_EMAIL: 'SEND_TEMPLATE_EMAIL'
    },
    TEMPLATES: {
        GAME_IS_OPEN_FOR_MEMBERS: 'GAME_IS_OPEN_FOR_MEMBERS',
        GAME_IS_OPEN_FOR_ALL: 'GAME_IS_OPEN_FOR_ALL',
        UPDATE_GAME_DETAILS: 'UPDATE_GAME_DETAILS'
    }
};