module.exports = {
    DASHBOARD_TYPE: {
        USER: 'USER_DASHBOARD',
        ADMIN: 'ADMIN_DASHBOARD'
    },
    CONTEXT: {
        OPEN_GAMES: 'OPEN_GAMES_NAV_CONTEXT',
        EDIT_USER_DATA: 'EDIT_USER_DATA_NAV_CONTEXT',
        USERS_DATA_LIST: 'USERS_DATA_LIST_NAV_CONTEXT',
        GAMES_LIST: 'GAMES_LIST_NAV_CONTEXT'
    }
};
