export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL';
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD = 'SIGN_UP_WITH_EMAIL_AND_PASSWORD';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const REPORT_ERROR = 'REPORT_ERROR';