'use strict';

var ACTIONS = {
    LOGIN: 'LOGIN',
    SOCIAL_LOGIN: 'SOCIAL_LOGIN',
    CREATE_USER: 'CREATE_USER',
    LOGOUT: 'LOGOUT',

    GET_USERS_DATA: 'GET_USERS_DATA',
    UPDATE_USER_DATA: 'UPDATE_USER_DATA',

    GET_GAMES: 'GET_GAMES',
    CREATE_GAME: 'CREATE_GAME',
    UPDATE_GAME: 'UPDATE_GAME',
    REMOVE_GAME: 'REMOVE_GAME',

    NAVIGATE_TO_PAGE: 'NAVIGATE_TO_PAGE',

    SHOW_DIALOG: 'SHOW_DIALOG',
    CLOSE_DIALOG: 'CLOSE_DIALOG'
};

module.exports = ACTIONS;
